Traceback (most recent call last):
  File "/var/folders/xl/zrhyjt457txb8kffxx2h908r0000gn/T/extract_13681007065834766465/scripts/4G_Network_Connection_Test.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
